version: '3'

services:
  linuxmint:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linuxmint-dev
    volumes:
      - ./:/home/developer/shared
      - test_data:/home/developer/.local
      - test_config:/home/developer/.config
    tty: true
    stdin_open: true
    command: -c "echo 'Linux Mint Development Environment' && echo 'Run ./setup_dev_environment.sh to start the setup' && /bin/bash"
    environment:
      - DEBIAN_FRONTEND=noninteractive
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined

volumes:
  test_data:
  test_config: 